### ISSUE TITLE
[TD-14-km] 메인화면 디자인 관련해서 상의 필요해요

### ISSUE THREAD

**Issue by boring-km** [boring-km/flutter_todo#20]
## Problem
메인화면 디자인이 너무 투박해서 슬슬 좀더 꾸며보려 하는데 아이디어 필요해요

## Description
![image](https://user-images.githubusercontent.com/34850203/109387418-ba950f00-7944-11eb-8e7d-da22241e761c.png)

## Alternatives
뒤에 배경 그림 넣고, 리스트뷰 부분은 반투명한 하얀색 위에 보이게 하는게 괜찮을까요?

**Comment by navyCK** [comment]
넵 폰트도 좀 바꾸면 더 괜찮을 것 같아요!

**Comment by boring-km** [comment]
Flutter 전체 기본 폰트 바꾸는 설정이 있는지 찾아봐야겠네요.
이거 따로 저거 따로 하다보면 화면에 통일성이 없을것 같아서요.
